Update de_de.json
Cosmetica-cc/Cosmetica pull request #92
Opened 2023-04-27 15:48 UTC by Cape-City

Fixed german translation

2023-04-27 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Cosmetica-cc/Cosmetica?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Cosmetica-cc/Cosmetica?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Cosmetica-cc/Cosmetica?pullRequest=92) it.</sub>

2023-05-20 13:04 UTC, valoeghese requested changes
Hallo und vielen dank für den Beitrag!

I've only one real question about this pull request. Once that's resolved it should be all good to merge.

2023-05-20 16:19 UTC, Cape-City commented
The 2 "Symbole" should be also "Icons". Icons is a well used word for gamers meanwhile in germany too. I'm "throwing" the lang-file in the first way through deepl.com and afterwards i check the translation for typos or not to understand translations for a german. I overseen this two, sorry for that. You're absolutly right, that it has to be more consistent.

How can i correct this now?

2023-05-23 23:34 UTC, valoeghese approved these changes

2023-05-23 23:35 UTC, merged